# Generated by Django 2.2.6 on 2020-10-23 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0008_auto_20201020_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.AlterField(
            model_name='group',
            name='active',
            field=models.BooleanField(default=True,
                                      verbose_name='Видимость группы на сайте'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(
                help_text='Напишите о чем эта группа, какие посты в ней будут',
                verbose_name='Описание группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(max_length=20, unique=True,
                                   verbose_name='Часть URL адреса группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=200,
                                   verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='posts', to=settings.AUTH_USER_MODEL,
                verbose_name='Автор поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True,
                                    help_text='Выберите группу или оставьте пустым',
                                    null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='posts', to='posts.Group',
                                    verbose_name='Группа для вашего поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True,
                                       verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='Текст вашего поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(
                help_text='Назовите пост или оставьте пустым', max_length=200,
                verbose_name='Название поста'),
        ),
    ]
