# Generated by Django 2.2.6 on 2020-10-19 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0004_auto_20201019_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'default_related_name': 'groups', 'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'default_related_name': 'posts',
                     'ordering': ['-pub_date']},
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='posts', to='posts.Group',
                                    verbose_name='Select a group to publish the post'),
        ),
    ]
