# Generated by Django 2.2.6 on 2020-10-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0007_auto_20201019_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(
                help_text='Write something amazing and awesome',
                max_length=200, null=True, verbose_name='Title your post'),
        ),
    ]
