# Generated by Django 2.2.6 on 2020-11-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20201023_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Назовите пост', max_length=200, verbose_name='Название поста'),
        ),
    ]
