# Generated by Django 3.1.4 on 2021-01-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Видимость на сайте'),
        ),
        migrations.AlterField(
            model_name='group',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Видимость на сайте'),
        ),
        migrations.AlterField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Видимость на сайте'),
        ),
    ]
