# Generated by Django 2.2.6 on 2020-10-19 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0005_auto_20201019_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'default_related_name': 'group', 'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Просто заголовок', max_length=200),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(
                help_text='Write something short but important. Max: 20 EN letters,numbers, underscores or hyphens.',
                max_length=20, unique=True,
                verbose_name='A part of yor Group URL'),
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True,
                                    help_text='Select a group to publish the post',
                                    null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='posts', to='posts.Group',
                                    verbose_name='A Group of your post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Make a good post today!',
                                   verbose_name='Text of your Post'),
        ),
    ]
